import { TrialMatch, CriterionResult } from "./types";

export const CONDITIONS_LIST = [
  "Type 2 Diabetes Mellitus",
  "Breast Cancer",
  "Non-Small Cell Lung Cancer",
  "Major Depressive Disorder",
  "Rheumatoid Arthritis",
  "Chronic Obstructive Pulmonary Disease",
  "Atrial Fibrillation",
  "Chronic Kidney Disease",
  "Alzheimer's Disease",
  "Multiple Sclerosis",
  "Crohn's Disease",
  "Ulcerative Colitis",
  "Psoriatic Arthritis",
  "Systemic Lupus Erythematosus",
  "Heart Failure",
  "Hypertension",
  "Asthma",
  "Parkinson's Disease",
  "Hepatitis C",
  "HIV/AIDS",
  "Pancreatic Cancer",
  "Colorectal Cancer",
  "Prostate Cancer",
  "Melanoma",
  "Glioblastoma",
  "Acute Myeloid Leukemia",
  "Chronic Lymphocytic Leukemia",
  "Non-Hodgkin Lymphoma",
  "Ovarian Cancer",
  "Sickle Cell Disease",
  "Cystic Fibrosis",
  "Epilepsy",
  "Migraine",
  "Osteoarthritis",
  "Fibromyalgia",
  "Irritable Bowel Syndrome",
  "Diabetic Neuropathy",
  "Diabetic Retinopathy",
  "Peripheral Artery Disease",
  "Deep Vein Thrombosis",
];

export const MEDICATIONS_LIST = [
  "Metformin",
  "Insulin Glargine",
  "Lisinopril",
  "Amlodipine",
  "Atorvastatin",
  "Metoprolol",
  "Omeprazole",
  "Levothyroxine",
  "Warfarin",
  "Apixaban",
  "Rivaroxaban",
  "Clopidogrel",
  "Sertraline",
  "Fluoxetine",
  "Escitalopram",
  "Duloxetine",
  "Gabapentin",
  "Pregabalin",
  "Prednisone",
  "Methylprednisolone",
  "Adalimumab",
  "Infliximab",
  "Etanercept",
  "Rituximab",
  "Pembrolizumab",
  "Nivolumab",
  "Tamoxifen",
  "Letrozole",
  "Ibuprofen",
  "Acetaminophen",
  "Hydrocodone",
  "Oxycodone",
  "Tramadol",
  "Amoxicillin",
  "Azithromycin",
  "Doxycycline",
  "Albuterol",
  "Fluticasone",
  "Montelukast",
  "Sitagliptin",
];

export const LAB_FIELDS = [
  { key: "hba1c", label: "HbA1c (%)", min: 4.0, max: 14.0, unit: "%" },
  { key: "creatinine", label: "Creatinine (mg/dL)", min: 0.5, max: 5.0, unit: "mg/dL" },
  { key: "egfr", label: "eGFR (mL/min)", min: 15, max: 120, unit: "mL/min" },
  { key: "alt", label: "ALT (U/L)", min: 5, max: 200, unit: "U/L" },
  { key: "ast", label: "AST (U/L)", min: 5, max: 200, unit: "U/L" },
  { key: "hemoglobin", label: "Hemoglobin (g/dL)", min: 7, max: 18, unit: "g/dL" },
  { key: "platelet_count", label: "Platelet Count (x10^9/L)", min: 50, max: 450, unit: "x10^9/L" },
  { key: "wbc", label: "WBC (x10^9/L)", min: 2, max: 15, unit: "x10^9/L" },
  { key: "total_cholesterol", label: "Total Cholesterol (mg/dL)", min: 100, max: 350, unit: "mg/dL" },
  { key: "ldl", label: "LDL (mg/dL)", min: 40, max: 250, unit: "mg/dL" },
];

// Condition → Category mapping (for the results-page category filter)
export const CONDITION_CATEGORY: Record<string, string> = {
  "Type 2 Diabetes Mellitus": "Diabetes",
  "Diabetic Neuropathy": "Diabetes",
  "Diabetic Retinopathy": "Diabetes",
  "Breast Cancer": "Cancer",
  "Non-Small Cell Lung Cancer": "Cancer",
  "Lung Neoplasms": "Cancer",
  "Triple Negative Breast Neoplasms": "Cancer",
  "Pancreatic Cancer": "Cancer",
  "Colorectal Cancer": "Cancer",
  "Prostate Cancer": "Cancer",
  "Melanoma": "Cancer",
  "Glioblastoma": "Cancer",
  "Acute Myeloid Leukemia": "Cancer",
  "Chronic Lymphocytic Leukemia": "Cancer",
  "Non-Hodgkin Lymphoma": "Cancer",
  "Ovarian Cancer": "Cancer",
  "Cardiovascular Disease": "Cardiovascular",
  "Heart Failure": "Cardiovascular",
  "Hypertension": "Cardiovascular",
  "Atrial Fibrillation": "Cardiovascular",
  "Peripheral Artery Disease": "Cardiovascular",
  "Deep Vein Thrombosis": "Cardiovascular",
  "Alzheimer's Disease": "Neurological",
  "Mild Cognitive Impairment": "Neurological",
  "Parkinson's Disease": "Neurological",
  "Multiple Sclerosis": "Neurological",
  "Epilepsy": "Neurological",
  "Migraine": "Neurological",
  "Major Depressive Disorder": "Neurological",
  "Rheumatoid Arthritis": "Autoimmune",
  "Psoriatic Arthritis": "Autoimmune",
  "Systemic Lupus Erythematosus": "Autoimmune",
  "Crohn's Disease": "Autoimmune",
  "Ulcerative Colitis": "Autoimmune",
  "Inflammatory Bowel Disease": "Autoimmune",
  "Asthma": "Pulmonary",
  "Chronic Obstructive Pulmonary Disease": "Pulmonary",
  "Cystic Fibrosis": "Pulmonary",
  "Obesity": "Cardiovascular",
};

// Unique criteria per trial — hand-written to reflect the actual medical context
const TRIAL_CRITERIA: Record<string, CriterionResult[]> = {
  NCT05243264: [
    { criterion: "Age", patientValue: "45 years", trialRequirement: "40 – 75", result: "match" },
    { criterion: "Type 2 Diabetes", patientValue: "Yes, dx 2020", trialRequirement: "Required", result: "match" },
    { criterion: "HbA1c", patientValue: "8.1%", trialRequirement: "7.0 – 10.5%", result: "match" },
    { criterion: "BMI", patientValue: "31.2 kg/m²", trialRequirement: "≥ 25 kg/m²", result: "match" },
    { criterion: "eGFR", patientValue: "82 mL/min", trialRequirement: "≥ 30 mL/min", result: "match" },
    { criterion: "Prior pancreatitis", patientValue: "None reported", trialRequirement: "No history", result: "match" },
  ],
  NCT06118823: [
    { criterion: "Age", patientValue: "58 years", trialRequirement: "≥ 18", result: "match" },
    { criterion: "Stage III NSCLC", patientValue: "IIIA", trialRequirement: "IIIA / IIIB", result: "match" },
    { criterion: "ECOG status", patientValue: "1", trialRequirement: "0 – 1", result: "match" },
    { criterion: "Prior anti-PD-1", patientValue: "None", trialRequirement: "None", result: "match" },
    { criterion: "Autoimmune disease", patientValue: "Not assessed", trialRequirement: "No active", result: "unknown" },
    { criterion: "CNS metastases", patientValue: "None", trialRequirement: "None active", result: "match" },
  ],
  NCT05891834: [
    { criterion: "Age", patientValue: "68 years", trialRequirement: "60 – 85", result: "match" },
    { criterion: "MMSE score", patientValue: "24", trialRequirement: "20 – 28", result: "match" },
    { criterion: "Amyloid PET", patientValue: "Not performed", trialRequirement: "Positive required", result: "unknown" },
    { criterion: "Study partner", patientValue: "Available", trialRequirement: "Required", result: "match" },
    { criterion: "Anticoagulants", patientValue: "Apixaban", trialRequirement: "None permitted", result: "excluded" },
    { criterion: "Cerebral microhemorrhages", patientValue: "Unknown", trialRequirement: "≤ 4 on MRI", result: "unknown" },
  ],
  NCT06234567: [
    { criterion: "Age", patientValue: "52 years", trialRequirement: "≥ 18", result: "match" },
    { criterion: "TNBC diagnosis", patientValue: "Confirmed, ER/PR/HER2-neg", trialRequirement: "Histologically confirmed", result: "match" },
    { criterion: "Prior therapies", patientValue: "2 lines", trialRequirement: "≥ 2 prior", result: "match" },
    { criterion: "ECOG status", patientValue: "1", trialRequirement: "0 – 1", result: "match" },
    { criterion: "Measurable disease", patientValue: "Yes (RECIST 1.1)", trialRequirement: "Required", result: "match" },
    { criterion: "UGT1A1*28 genotype", patientValue: "Not tested", trialRequirement: "Not homozygous", result: "unknown" },
  ],
  NCT05567890: [
    { criterion: "Age", patientValue: "49 years", trialRequirement: "18 – 75", result: "match" },
    { criterion: "RA diagnosis", patientValue: "ACR/EULAR 2010", trialRequirement: "Required", result: "match" },
    { criterion: "DAS28-CRP", patientValue: "4.8", trialRequirement: "≥ 3.2", result: "match" },
    { criterion: "Methotrexate trial", patientValue: "14 weeks", trialRequirement: "≥ 12 weeks", result: "match" },
    { criterion: "Prior biologic", patientValue: "Etanercept (3 mo)", trialRequirement: "No prior biologic", result: "excluded" },
    { criterion: "Tuberculosis screen", patientValue: "Negative (2025)", trialRequirement: "No active TB", result: "match" },
  ],
  NCT06678901: [
    { criterion: "Age", patientValue: "62 years", trialRequirement: "≥ 40", result: "match" },
    { criterion: "LVEF", patientValue: "52%", trialRequirement: "≥ 45%", result: "match" },
    { criterion: "BMI", patientValue: "34.5 kg/m²", trialRequirement: "≥ 30 kg/m²", result: "match" },
    { criterion: "NYHA class", patientValue: "II", trialRequirement: "II – III", result: "match" },
    { criterion: "NT-proBNP", patientValue: "Not measured", trialRequirement: "≥ 300 pg/mL", result: "unknown" },
    { criterion: "Current GLP-1 RA", patientValue: "Semaglutide 1mg", trialRequirement: "None", result: "excluded" },
  ],
  NCT05789012: [
    { criterion: "Age", patientValue: "29 years", trialRequirement: "18 – 80", result: "match" },
    { criterion: "Crohn's diagnosis", patientValue: "5 years", trialRequirement: "≥ 3 months", result: "match" },
    { criterion: "CDAI score", patientValue: "Not calculated", trialRequirement: "220 – 450", result: "unknown" },
    { criterion: "Prior biologic failure", patientValue: "None — treatment-naive", trialRequirement: "≥ 1 failed biologic", result: "excluded" },
    { criterion: "Colitis type", patientValue: "Crohn's", trialRequirement: "Not UC / indeterminate", result: "match" },
    { criterion: "Prior IL-23 p19 inhibitor", patientValue: "None", trialRequirement: "None permitted", result: "match" },
  ],
  NCT06345678: [
    { criterion: "Age", patientValue: "68 years", trialRequirement: "50 – 90", result: "match" },
    { criterion: "AD diagnosis", patientValue: "Mild AD dementia", trialRequirement: "MCI or mild AD", result: "match" },
    { criterion: "Amyloid confirmation", patientValue: "Pending", trialRequirement: "PET or CSF positive", result: "unknown" },
    { criterion: "MMSE score", patientValue: "19", trialRequirement: "≥ 22", result: "excluded" },
    { criterion: "Anticoagulants", patientValue: "Apixaban", trialRequirement: "None permitted", result: "excluded" },
    { criterion: "eGFR", patientValue: "41 mL/min", trialRequirement: "≥ 30 mL/min", result: "match" },
  ],
  NCT05901234: [
    { criterion: "Age", patientValue: "45 years", trialRequirement: "12 – 17", result: "excluded" },
    { criterion: "Physician-dx asthma", patientValue: "Yes, 15 years", trialRequirement: "≥ 12 months", result: "match" },
    { criterion: "Blood eosinophils", patientValue: "Not checked", trialRequirement: "≥ 150 cells/μL", result: "unknown" },
    { criterion: "Recent exacerbation", patientValue: "None in 12 mo", trialRequirement: "≥ 1 severe", result: "excluded" },
    { criterion: "Current smoker", patientValue: "Never", trialRequirement: "Non-smoker", result: "match" },
    { criterion: "Prior IL-4/13 therapy", patientValue: "None", trialRequirement: "None permitted", result: "match" },
  ],
  NCT06012345: [
    { criterion: "Age", patientValue: "45 years", trialRequirement: "18 – 65", result: "match" },
    { criterion: "UC diagnosis", patientValue: "Moderate UC, dx 2019", trialRequirement: "Required", result: "match" },
    { criterion: "Mayo score", patientValue: "Not calculated", trialRequirement: "6 – 12", result: "unknown" },
    { criterion: "OL induction response", patientValue: "Not enrolled", trialRequirement: "Required", result: "excluded" },
    { criterion: "Cardiac arrhythmia", patientValue: "None", trialRequirement: "No history", result: "match" },
    { criterion: "Serious infection", patientValue: "None active", trialRequirement: "None active", result: "match" },
  ],
};

export const MOCK_TRIALS: TrialMatch[] = [
  {
    nctId: "NCT05243264",
    briefTitle: "Tirzepatide vs Insulin Glargine in Type 2 Diabetes With Cardiovascular Risk",
    officialTitle: "A Randomized, Open-Label, Phase 3 Study Comparing Tirzepatide to Insulin Glargine in Participants With Type 2 Diabetes Mellitus and Increased Cardiovascular Risk",
    sponsor: "Eli Lilly and Company",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 3250,
    briefSummary: "This study compares tirzepatide, a dual GIP/GLP-1 receptor agonist, with insulin glargine in adults with type 2 diabetes who have elevated cardiovascular risk. The primary outcome is time to first major adverse cardiovascular event (MACE) over 54 months of follow-up.",
    detailedDescription: "Type 2 diabetes mellitus (T2DM) affects over 400 million people globally and is a leading risk factor for cardiovascular disease. Tirzepatide has shown superior glycemic control and weight reduction compared to existing therapies. This trial aims to demonstrate cardiovascular benefit in a high-risk population.",
    conditions: ["Type 2 Diabetes Mellitus", "Cardiovascular Disease"],
    interventions: ["Tirzepatide 15mg subcutaneous weekly", "Insulin Glargine titrated to fasting glucose target"],
    eligibilityCriteria: "Inclusion Criteria:\n- Adults aged 40-75 with type 2 diabetes\n- HbA1c between 7.0% and 10.5%\n- Established cardiovascular disease OR high cardiovascular risk\n- BMI >= 25 kg/m2\n\nExclusion Criteria:\n- Type 1 diabetes\n- eGFR < 30 mL/min/1.73m2\n- History of pancreatitis\n- Current use of GLP-1 receptor agonists\n- Severe gastroparesis",
    matchScore: 94,
    criteriaResults: TRIAL_CRITERIA["NCT05243264"],
    locations: [
      { facility: "Mayo Clinic", city: "Rochester", state: "MN", country: "United States", lat: 44.0225, lng: -92.4699, distance: 12.3 },
      { facility: "Cleveland Clinic", city: "Cleveland", state: "OH", country: "United States", lat: 41.5034, lng: -81.6212, distance: 142.7 },
      { facility: "Massachusetts General Hospital", city: "Boston", state: "MA", country: "United States", lat: 42.3631, lng: -71.0686, distance: 856.2 },
    ],
    nearestDistance: 12.3,
    lastUpdated: "2026-03-15",
    contactName: "Dr. Sarah Mitchell",
    contactEmail: "mitchell.sarah@mayo.edu",
    contactPhone: "(507) 284-2511",
  },
  {
    nctId: "NCT06118823",
    briefTitle: "Pembrolizumab Plus Chemotherapy in Stage III Non-Small Cell Lung Cancer",
    officialTitle: "A Phase 2, Randomized Study of Neoadjuvant Pembrolizumab Combined With Platinum-Based Chemotherapy Followed by Surgical Resection and Adjuvant Pembrolizumab in Stage III NSCLC",
    sponsor: "Merck Sharp & Dohme LLC",
    phase: "Phase 2",
    status: "Recruiting",
    enrollmentCount: 420,
    briefSummary: "This study evaluates the efficacy and safety of pembrolizumab combined with platinum-doublet chemotherapy as neoadjuvant therapy, followed by surgery and adjuvant pembrolizumab, in participants with resectable stage III non-small cell lung cancer (NSCLC).",
    detailedDescription: "Neoadjuvant immunotherapy combined with chemotherapy has transformed the treatment landscape for resectable NSCLC. This trial builds on the KEYNOTE program to evaluate whether perioperative pembrolizumab can improve pathological complete response rates and event-free survival in stage III disease.",
    conditions: ["Non-Small Cell Lung Cancer", "Lung Neoplasms"],
    interventions: ["Pembrolizumab 200mg IV every 3 weeks", "Cisplatin + Pemetrexed (non-squamous) or Cisplatin + Gemcitabine (squamous)"],
    eligibilityCriteria: "Inclusion Criteria:\n- Age >= 18 years\n- Histologically confirmed stage IIIA/IIIB NSCLC\n- ECOG performance status 0-1\n- Adequate organ function\n- No prior systemic therapy for current lung cancer\n\nExclusion Criteria:\n- Active autoimmune disease requiring systemic treatment\n- Prior anti-PD-1/PD-L1/PD-L2 therapy\n- Active CNS metastases\n- Current use of immunosuppressive agents\n- Known HIV, HBV, or HCV infection",
    matchScore: 87,
    criteriaResults: TRIAL_CRITERIA["NCT06118823"],
    locations: [
      { facility: "MD Anderson Cancer Center", city: "Houston", state: "TX", country: "United States", lat: 29.7071, lng: -95.3976, distance: 45.8 },
      { facility: "Memorial Sloan Kettering", city: "New York", state: "NY", country: "United States", lat: 40.7641, lng: -73.9568, distance: 234.5 },
    ],
    nearestDistance: 45.8,
    lastUpdated: "2026-02-28",
    contactName: "Dr. James Chen",
    contactEmail: "jchen@mdanderson.org",
    contactPhone: "(713) 792-6363",
  },
  {
    nctId: "NCT05891834",
    briefTitle: "Donanemab in Early Symptomatic Alzheimer's Disease",
    officialTitle: "A Phase 3, Multicenter, Randomized, Double-Blind, Placebo-Controlled Study of Donanemab in Participants With Early Symptomatic Alzheimer's Disease",
    sponsor: "Eli Lilly and Company",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 1800,
    briefSummary: "This study evaluates the safety and efficacy of donanemab, an anti-amyloid antibody targeting N3pG amyloid-beta, in slowing cognitive and functional decline in participants with early symptomatic Alzheimer's disease confirmed by amyloid PET imaging.",
    detailedDescription: "Alzheimer's disease affects an estimated 6.7 million Americans. Donanemab has previously demonstrated significant amyloid plaque clearance and slowing of clinical decline. This confirmatory trial expands enrollment criteria to include a broader population while maintaining amyloid PET confirmation.",
    conditions: ["Alzheimer's Disease", "Mild Cognitive Impairment"],
    interventions: ["Donanemab 700mg/1400mg IV every 4 weeks", "Placebo IV every 4 weeks"],
    eligibilityCriteria: "Inclusion Criteria:\n- Age 60-85 years\n- Gradual progressive cognitive decline over >= 6 months\n- MMSE score 20-28\n- Positive amyloid PET scan\n- Reliable study partner available\n\nExclusion Criteria:\n- Non-AD dementia\n- More than 4 cerebral microhemorrhages on MRI\n- Current anticoagulant therapy\n- Stroke or seizure within 12 months\n- Chronic kidney disease stage 4-5",
    matchScore: 72,
    criteriaResults: TRIAL_CRITERIA["NCT05891834"],
    locations: [
      { facility: "Johns Hopkins University", city: "Baltimore", state: "MD", country: "United States", lat: 39.2979, lng: -76.5928, distance: 78.4 },
      { facility: "UCSF Memory and Aging Center", city: "San Francisco", state: "CA", country: "United States", lat: 37.7631, lng: -122.4576, distance: 1847.3 },
      { facility: "Banner Alzheimer's Institute", city: "Phoenix", state: "AZ", country: "United States", lat: 33.4746, lng: -112.0634, distance: 1423.6 },
    ],
    nearestDistance: 78.4,
    lastUpdated: "2026-03-01",
    contactName: "Dr. Rebecca Torres",
    contactEmail: "rtorres@jhmi.edu",
    contactPhone: "(410) 955-9441",
  },
  {
    nctId: "NCT06234567",
    briefTitle: "Sacituzumab Govitecan in Metastatic Triple-Negative Breast Cancer",
    officialTitle: "A Phase 3 Open-Label Study of Sacituzumab Govitecan vs Treatment of Physician's Choice in Patients With Previously Treated Metastatic Triple-Negative Breast Cancer",
    sponsor: "Gilead Sciences",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 560,
    briefSummary: "This trial evaluates sacituzumab govitecan, a Trop-2-directed antibody-drug conjugate, compared to single-agent chemotherapy in patients with metastatic triple-negative breast cancer who have received at least two prior systemic therapies.",
    detailedDescription: "Triple-negative breast cancer (TNBC) accounts for approximately 15% of all breast cancers and has limited treatment options. Sacituzumab govitecan has shown promise in earlier studies. This study aims to confirm progression-free survival and overall survival benefit in a pre-treated population.",
    conditions: ["Triple Negative Breast Neoplasms", "Breast Cancer"],
    interventions: ["Sacituzumab govitecan 10mg/kg IV days 1 and 8 of 21-day cycle", "Physician's choice chemotherapy"],
    eligibilityCriteria: "Inclusion Criteria:\n- Female or male, age >= 18 years\n- Histologically confirmed TNBC (ER < 1%, PR < 1%, HER2-negative)\n- At least 2 prior systemic therapies for metastatic disease\n- ECOG 0-1\n- Measurable disease per RECIST 1.1\n\nExclusion Criteria:\n- Active CNS metastases (treated and stable allowed)\n- Prior Trop-2-directed therapy\n- Severe hepatic impairment\n- UGT1A1*28 homozygous genotype\n- Active interstitial lung disease",
    matchScore: 82,
    criteriaResults: TRIAL_CRITERIA["NCT06234567"],
    locations: [
      { facility: "Dana-Farber Cancer Institute", city: "Boston", state: "MA", country: "United States", lat: 42.3370, lng: -71.1056, distance: 862.1 },
      { facility: "UCLA Jonsson Comprehensive Cancer Center", city: "Los Angeles", state: "CA", country: "United States", lat: 34.0664, lng: -118.4464, distance: 1553.8 },
    ],
    nearestDistance: 862.1,
    lastUpdated: "2026-02-10",
    contactName: "Dr. Allison Park",
    contactEmail: "apark@dana-farber.org",
    contactPhone: "(617) 632-3000",
  },
  {
    nctId: "NCT05567890",
    briefTitle: "Upadacitinib vs Adalimumab in Moderate-to-Severe Rheumatoid Arthritis",
    officialTitle: "A Phase 3b, Randomized, Double-Blind Study Comparing Upadacitinib to Adalimumab as First-Line Advanced Therapy in Patients With Moderate-to-Severe Rheumatoid Arthritis and Inadequate Response to Methotrexate",
    sponsor: "AbbVie Inc.",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 890,
    briefSummary: "This head-to-head study compares the JAK inhibitor upadacitinib with the TNF inhibitor adalimumab in rheumatoid arthritis patients who have not achieved adequate response with methotrexate alone.",
    detailedDescription: "Rheumatoid arthritis affects approximately 1.3 million Americans. While biologic therapies have improved outcomes significantly, comparative data between JAK inhibitors and TNF inhibitors in the first-line advanced therapy setting remain limited. This trial addresses this evidence gap.",
    conditions: ["Rheumatoid Arthritis"],
    interventions: ["Upadacitinib 15mg oral daily", "Adalimumab 40mg subcutaneous every 2 weeks"],
    eligibilityCriteria: "Inclusion Criteria:\n- Adults aged 18-75 years\n- Diagnosis of RA per ACR/EULAR 2010 criteria\n- Active disease (DAS28-CRP >= 3.2, >= 6 tender + 6 swollen joints)\n- Inadequate response to methotrexate >= 12 weeks\n- No prior biologic or JAK inhibitor therapy\n\nExclusion Criteria:\n- History of or current serious infection\n- Active tuberculosis\n- Current use of strong CYP3A4 inhibitors\n- History of VTE or PE\n- Platelet count < 100 x10^9/L",
    matchScore: 68,
    criteriaResults: TRIAL_CRITERIA["NCT05567890"],
    locations: [
      { facility: "Hospital for Special Surgery", city: "New York", state: "NY", country: "United States", lat: 40.7645, lng: -73.9545, distance: 236.2 },
      { facility: "Stanford Health Care", city: "Stanford", state: "CA", country: "United States", lat: 37.4346, lng: -122.1750, distance: 1803.5 },
      { facility: "Brigham and Women's Hospital", city: "Boston", state: "MA", country: "United States", lat: 42.3358, lng: -71.1068, distance: 860.3 },
    ],
    nearestDistance: 236.2,
    lastUpdated: "2026-01-22",
    contactName: "Dr. Michael Rivera",
    contactEmail: "mrivera@hss.edu",
    contactPhone: "(212) 606-1000",
  },
  {
    nctId: "NCT06678901",
    briefTitle: "Semaglutide for Heart Failure With Preserved Ejection Fraction and Obesity",
    officialTitle: "A Phase 3, Randomized, Double-Blind, Placebo-Controlled Trial of Semaglutide 2.4mg in Participants With Heart Failure With Preserved Ejection Fraction and BMI >= 30",
    sponsor: "Novo Nordisk",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 1650,
    briefSummary: "This trial investigates whether semaglutide 2.4mg weekly improves symptoms, physical limitations, and cardiovascular outcomes in patients with heart failure with preserved ejection fraction (HFpEF) and obesity. The primary endpoint is a hierarchical composite of cardiovascular death, heart failure events, and change in KCCQ score.",
    detailedDescription: "HFpEF accounts for approximately half of all heart failure cases and has limited proven therapies. Obesity is both a risk factor and driver of HFpEF pathophysiology through inflammation, volume overload, and metabolic dysfunction. GLP-1 receptor agonists have shown cardiovascular benefits in diabetes trials and preliminary data suggest benefit in HFpEF with obesity.",
    conditions: ["Heart Failure", "Obesity"],
    interventions: ["Semaglutide 2.4mg subcutaneous weekly", "Placebo subcutaneous weekly"],
    eligibilityCriteria: "Inclusion Criteria:\n- Age >= 40 years\n- LVEF >= 45%\n- BMI >= 30 kg/m2\n- NYHA class II-III symptoms\n- NT-proBNP >= 300 pg/mL (or >= 600 if atrial fibrillation)\n- At least one HF hospitalization within 12 months OR ongoing diuretic use\n\nExclusion Criteria:\n- Type 1 diabetes\n- eGFR < 20 mL/min\n- Prior bariatric surgery\n- Current GLP-1 RA use\n- Severe valvular disease\n- Planned cardiac surgery",
    matchScore: 55,
    criteriaResults: TRIAL_CRITERIA["NCT06678901"],
    locations: [
      { facility: "Duke University Medical Center", city: "Durham", state: "NC", country: "United States", lat: 36.0085, lng: -78.9285, distance: 320.6 },
      { facility: "Northwestern Memorial Hospital", city: "Chicago", state: "IL", country: "United States", lat: 41.8953, lng: -87.6211, distance: 410.2 },
    ],
    nearestDistance: 320.6,
    lastUpdated: "2026-03-08",
    contactName: "Dr. Lisa Chang",
    contactEmail: "lchang@duke.edu",
    contactPhone: "(919) 668-8111",
  },
  {
    nctId: "NCT05789012",
    briefTitle: "Risankizumab Induction and Maintenance in Moderate-to-Severe Crohn's Disease",
    officialTitle: "A Phase 3, Randomized, Double-Blind Study of Risankizumab Induction Followed by Randomized Withdrawal in Participants With Moderate-to-Severe Crohn's Disease Who Have Failed Prior Biologic Therapy",
    sponsor: "AbbVie Inc.",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 720,
    briefSummary: "This study evaluates the safety and efficacy of risankizumab, an anti-IL-23 antibody, as induction and maintenance therapy in patients with moderate-to-severe Crohn's disease who have had inadequate response or intolerance to at least one prior biologic therapy.",
    detailedDescription: "Crohn's disease is a chronic inflammatory condition affecting approximately 780,000 Americans. Many patients lose response to initial biologic therapies over time. Risankizumab targets the p19 subunit of IL-23, a cytokine central to intestinal inflammation, offering a distinct mechanism from anti-TNF and anti-integrin therapies.",
    conditions: ["Crohn's Disease", "Inflammatory Bowel Disease"],
    interventions: ["Risankizumab 600mg IV induction then 360mg SC maintenance", "Placebo"],
    eligibilityCriteria: "Inclusion Criteria:\n- Adults 18-80 years\n- Crohn's disease diagnosed >= 3 months\n- CDAI 220-450\n- SES-CD >= 6 (or >= 4 for isolated ileal disease)\n- Failed or intolerant to >= 1 biologic\n\nExclusion Criteria:\n- Ulcerative colitis or indeterminate colitis\n- Short bowel syndrome\n- Active perianal fistula requiring surgery\n- Current abscess\n- Prior IL-23 p19 inhibitor use",
    matchScore: 41,
    criteriaResults: TRIAL_CRITERIA["NCT05789012"],
    locations: [
      { facility: "Mount Sinai Hospital", city: "New York", state: "NY", country: "United States", lat: 40.7900, lng: -73.9526, distance: 233.1 },
      { facility: "Cedars-Sinai Medical Center", city: "Los Angeles", state: "CA", country: "United States", lat: 34.0762, lng: -118.3801, distance: 1548.9 },
    ],
    nearestDistance: 233.1,
    lastUpdated: "2026-02-05",
    contactName: "Dr. Karen Walsh",
    contactEmail: "kwalsh@mountsinai.org",
    contactPhone: "(212) 241-6500",
  },
  {
    nctId: "NCT06345678",
    briefTitle: "Lecanemab Subcutaneous Formulation in Early Alzheimer's Disease",
    officialTitle: "A Phase 3, Open-Label Study Evaluating the Pharmacokinetics, Safety, and Efficacy of Subcutaneous Lecanemab in Participants With Early Alzheimer's Disease",
    sponsor: "Eisai Inc.",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 940,
    briefSummary: "This study evaluates a subcutaneous formulation of lecanemab for convenience and comparable efficacy to the approved intravenous formulation in participants with mild cognitive impairment or mild dementia due to Alzheimer's disease.",
    detailedDescription: "Lecanemab received full FDA approval based on demonstrated reduction in amyloid plaques and slowing of clinical decline. The current IV formulation requires biweekly infusions at treatment centers. A subcutaneous option could improve access and adherence by enabling at-home administration.",
    conditions: ["Alzheimer's Disease"],
    interventions: ["Lecanemab SC weekly auto-injector", "Lecanemab 10mg/kg IV biweekly (reference)"],
    eligibilityCriteria: "Inclusion Criteria:\n- Age 50-90 years\n- MCI due to AD or mild AD dementia\n- Amyloid-positive by PET or CSF\n- MMSE >= 22\n- Stable medications for >= 30 days\n\nExclusion Criteria:\n- Non-AD neurological condition\n- More than 4 microhemorrhages on MRI\n- Anticoagulant use\n- Severe renal impairment (eGFR < 30)\n- Known ARIA risk factors",
    matchScore: 38,
    criteriaResults: TRIAL_CRITERIA["NCT06345678"],
    locations: [
      { facility: "University of Pennsylvania", city: "Philadelphia", state: "PA", country: "United States", lat: 39.9522, lng: -75.1932, distance: 154.2 },
    ],
    nearestDistance: 154.2,
    lastUpdated: "2026-01-30",
    contactName: "Dr. Daniel Kim",
    contactEmail: "dkim@pennmedicine.upenn.edu",
    contactPhone: "(215) 662-7810",
  },
  {
    nctId: "NCT05901234",
    briefTitle: "Dupilumab in Uncontrolled Moderate-to-Severe Asthma in Adolescents",
    officialTitle: "A Phase 3, Randomized, Double-Blind, Placebo-Controlled Study of Dupilumab in Adolescents Aged 12-17 With Uncontrolled Moderate-to-Severe Asthma and Type 2 Inflammatory Phenotype",
    sponsor: "Sanofi / Regeneron",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 350,
    briefSummary: "This trial evaluates dupilumab, an anti-IL-4/IL-13 antibody, in reducing severe asthma exacerbations in adolescents with uncontrolled moderate-to-severe asthma characterized by eosinophilic or type 2 inflammation despite medium-to-high dose inhaled corticosteroids.",
    detailedDescription: "Asthma affects over 4 million adolescents in the United States. Severe uncontrolled asthma disproportionately impacts quality of life, school attendance, and physical activity. While dupilumab has demonstrated efficacy in adults, dedicated adolescent data will help guide treatment decisions in this population.",
    conditions: ["Asthma"],
    interventions: ["Dupilumab 200mg or 300mg SC every 2 weeks", "Placebo SC every 2 weeks"],
    eligibilityCriteria: "Inclusion Criteria:\n- Age 12-17 years\n- Physician-diagnosed asthma >= 12 months\n- Blood eosinophils >= 150 cells/uL or FeNO >= 25 ppb\n- >= 1 severe exacerbation in past 12 months\n- Medium-to-high dose ICS + LABA for >= 3 months\n\nExclusion Criteria:\n- Other chronic lung disease\n- Current smoker (including e-cigarettes)\n- Body weight < 30 kg\n- Helminth infection\n- Prior IL-4/IL-13 targeted therapy",
    matchScore: 29,
    criteriaResults: TRIAL_CRITERIA["NCT05901234"],
    locations: [
      { facility: "Children's Hospital of Philadelphia", city: "Philadelphia", state: "PA", country: "United States", lat: 39.9480, lng: -75.1935, distance: 155.0 },
      { facility: "Nationwide Children's Hospital", city: "Columbus", state: "OH", country: "United States", lat: 39.9543, lng: -82.9869, distance: 380.7 },
      { facility: "Texas Children's Hospital", city: "Houston", state: "TX", country: "United States", lat: 29.7089, lng: -95.4016, distance: 980.3 },
    ],
    nearestDistance: 155.0,
    lastUpdated: "2026-03-20",
    contactName: "Dr. Priya Sharma",
    contactEmail: "psharma@chop.edu",
    contactPhone: "(215) 590-3749",
  },
  {
    nctId: "NCT06012345",
    briefTitle: "Ozanimod Maintenance Therapy in Moderate-to-Severe Ulcerative Colitis",
    officialTitle: "A Phase 3, Randomized Withdrawal Study of Ozanimod Maintenance Therapy in Participants With Moderately-to-Severely Active Ulcerative Colitis Who Achieved Clinical Response During Open-Label Induction",
    sponsor: "Bristol-Myers Squibb",
    phase: "Phase 3",
    status: "Recruiting",
    enrollmentCount: 480,
    briefSummary: "This maintenance study evaluates sustained efficacy of ozanimod, an oral sphingosine 1-phosphate receptor modulator, in patients with ulcerative colitis who achieved clinical response during a 12-week open-label induction period.",
    detailedDescription: "Ulcerative colitis is a chronic inflammatory bowel disease affecting approximately 900,000 Americans. Despite advances in biologic therapies, many patients prefer oral treatment options. Ozanimod offers an oral, once-daily alternative that modulates lymphocyte trafficking without broad immunosuppression.",
    conditions: ["Ulcerative Colitis", "Inflammatory Bowel Disease"],
    interventions: ["Ozanimod 0.92mg oral daily", "Placebo oral daily"],
    eligibilityCriteria: "Inclusion Criteria:\n- Adults 18-65 years\n- Moderately-to-severely active UC (Mayo score 6-12)\n- Inadequate response to >= 1 conventional therapy\n- Clinical response achieved during OL induction\n\nExclusion Criteria:\n- Crohn's disease\n- Toxic megacolon or fulminant colitis\n- History of cardiac arrhythmia\n- Current macular edema\n- Active serious infection",
    matchScore: 63,
    criteriaResults: TRIAL_CRITERIA["NCT06012345"],
    locations: [
      { facility: "University of Chicago Medicine", city: "Chicago", state: "IL", country: "United States", lat: 41.7891, lng: -87.6047, distance: 415.8 },
      { facility: "Cleveland Clinic Florida", city: "Weston", state: "FL", country: "United States", lat: 26.1008, lng: -80.3998, distance: 1120.4 },
    ],
    nearestDistance: 415.8,
    lastUpdated: "2026-02-18",
    contactName: "Dr. Robert Nguyen",
    contactEmail: "rnguyen@uchicago.edu",
    contactPhone: "(773) 702-1000",
  },
];

export const FEATURED_CONDITIONS = [
  { name: "Cancer", count: 18420, icon: "ribbon" },
  { name: "Diabetes", count: 8340, icon: "activity" },
  { name: "Heart Disease", count: 6215, icon: "heart" },
  { name: "Alzheimer's", count: 3890, icon: "brain" },
  { name: "Autoimmune", count: 5670, icon: "shield" },
  { name: "Rare Diseases", count: 4120, icon: "dna" },
];
